name: Automation Test Full Headless
on: workflow_dispatch

concurrency:
  group: automation-full-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
          scope: '@openfin'

      - name: Restore root node_modules from cache
        id: node-cache
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm ci

      - name: Run JavaScript Tests with Mocha
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-mocha --prefix how-to/automation-testing/register-with-home-js

      - name: Run WDIO tests
        run: |
          npm run kill --prefix how-to/automation-testing/wdio
          npm run dos --prefix how-to/automation-testing/wdio
          npm run test --prefix how-to/automation-testing/wdio

      - name: Run Selenium tests
        run: |
          npm run kill --prefix how-to/automation-testing/selenium
          npm run dos --prefix how-to/automation-testing/selenium
          npm run test --prefix how-to/automation-testing/selenium

      - name: Run JavaScript Tests with Jasmine
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-jasmine --prefix how-to/automation-testing/register-with-home-js

      - name: Run JavaScript Tests with Jest
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-jest --prefix how-to/automation-testing/register-with-home-js

      - name: Run TypeScript Tests with Mocha
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-mocha --prefix how-to/automation-testing/register-with-home-ts

      - name: Run TypeScript Tests with Jasmine
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-jasmine --prefix how-to/automation-testing/register-with-home-ts

      - name: Run TypeScript Tests with Jest
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-jest --prefix how-to/automation-testing/register-with-home-ts

      - name: Run JavaScript Tests with Mocha for Store
        run: |
          npx fkill-cli OpenFin OpenFinRVM --force --silent
          npm run test-remote-mocha --prefix how-to/automation-testing/register-with-store-js
