name: GitHub Demo Packaging
on: [push]
jobs:
  Build-Package-Workspace-Starter:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} / ${{steps.extract_branch.outputs.branch}} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - run: echo "ğŸ This job's status is ${{ job.status }}."
      - name: Setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run package-how-tos
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Deploy ğŸš€
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy
          target-folder: steps.extract_branch.outputs.branch